src/Acme/DemoBundle/Entity/User.php
<?php

namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity
 * @UniqueEntity(fields="email", message="Email already taken")
 * @UniqueEntity(fields="username", message="Username already taken")
 * @UniqueEntity(fields="nick", message="Nick already taken")
 */
class User implements UserInterface, \Serializable {
    
    
    private $all_roles = array(
        'ROLE_ADMIN'=>'Administrator',//administrator role
        'ROLE_USER'=>'Redaktor'// editor role
        );
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;
    
    /**
     * @ORM\Column(type="string", length=25, unique=false)
     */
    private $name;
    
    /**
     * @ORM\Column(type="string", length=25, unique=false)
     */
    private $surname;
    
    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $nick;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $salt;
    
    /**
     * @ORM\Column(type="string", length=50)
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    public function __construct() {
        $this->isActive = true;
        $this->salt = '';
    } 
    
    
     /**
     * @inheritDoc
     */
    public function getId() {
        return $this->id;
    }
    public function setUsername($username) {
        $this->username = $username;
    }

    public function setName($name) {
        $this->name = $name;
    }

    public function setSurname($surname) {
        $this->surname = $surname;
    }

    public function setNick($nick) {
        $this->nick = $nick;
    }

    public function setSalt($salt) {
        $this->salt = $salt;
    }
    
    public function setRole($role) {
        $this->role = $role;
    }

    public function setPassword($password) {
        $this->password = md5($password);
    }

    public function setEmail($email) {
        $this->email = $email;
    }

    public function setIsActive($isActive) {
        $this->isActive = $isActive;
    }

        /**
     * @inheritDoc
     */
    public function getUsername() {
        return $this->username;
    }
    
     /**
     * @inheritDoc
     */
    public function getName() {
        return $this->name;
    }
    
    /**
     * @inheritDoc
     */
    public function getSurname() {
        return $this->surname;
    }
    
    /**
     * @inheritDoc
     */
    public function getNick() {
        return $this->nick;
    }
    
    /**
     * @inheritDoc
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * @inheritDoc
     */
    public function getSalt() {
        return '';
        //return $this->salt;
    }

    /**
     * @inheritDoc
     */
    public function getPassword() {
        return $this->password;
    }

    /**
     * @inheritDoc
     */
    public function getRole() {
        return $this->role;
    }
    
    /**
     * @inheritDoc
     */
    public function getRoles() {
        return array($this->role);
    }
    
    
    public function getRoleByName(){
        
        return $this->all_roles[$this->role];
            
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials() {
        
    }

    /**
     * @see \Serializable::serialize()
     */
    public function serialize() {
        return serialize(array(
                    $this->id,
                ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized) {
        list (
                $this->id,
                ) = unserialize($serialized);
    }

    public function __toString() {
        return $this->name . ' ' . $this->surname;
    }


    /**
     * Get isActive
     *
     * @return integer 
     */
    public function getIsActive()
    {
        return true;
    }
}

src/Acme/DemoBundle/Form/UserType.php
<?php

namespace Acme\DemoBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;


class UserType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('surname')
            ->add('nick')
            ->add('username')
            ->add('password','password',array('required' => true))
            ->add('email', 'email')  
            ->add('role','choice',array('choices' => array('ROLE_USER' => 'Redaktor', 'ROLE_ADMIN' => 'Administrator')));    
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Acme\DemoBundle\Entity\User'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'acme_demobundle_user';
    }
}

src/Acme/DemoBundle/Controller/UserController.php
<?php

namespace Acme\DemoBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Acme\DemoBundle\Entity\User;
use Acme\DemoBundle\Form\UserType;

/**
 * User controller.
 *
 * @Route("/user")
 */
class UserController extends Controller
{

    /**
     * Lists all User entities.
     *
     * @Route("/", name="user")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('AcmeDemoBundle:User')->findAll();

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new User entity.
     *
     * @Route("/", name="user_create")
     * @Method("POST")
     * @Template("AcmeDemoBundle:User:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new User();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('user_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
    * Creates a form to create a User entity.
    *
    * @param User $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createCreateForm(User $entity)
    {
        $form = $this->createForm(new UserType(), $entity, array(
            'action' => $this->generateUrl('user_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new User entity.
     *
     * @Route("/new", name="user_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new User();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a User entity.
     *
     * @Route("/{id}", name="user_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AcmeDemoBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing User entity.
     *
     * @Route("/{id}/edit", name="user_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AcmeDemoBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a User entity.
    *
    * @param User $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(User $entity)
    {
        $form = $this->createForm(new UserType(), $entity, array(
            'action' => $this->generateUrl('user_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing User entity.
     *
     * @Route("/{id}", name="user_update")
     * @Method("PUT")
     * @Template("AcmeDemoBundle:User:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AcmeDemoBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $deleteForm = $this->createDeleteForm($id);                  
         
        $editForm = $this->createEditForm($entity);
            
        if($entity->getPassword()==md5('')){            
         //$editForm->offsetUnset('password');
         //$editForm->remove('password');            
        }
        
        $editForm->handleRequest($request);
                
        
        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('user_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a User entity.
     *
     * @Route("/{id}", name="user_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('AcmeDemoBundle:User')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find User entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('user'));
    }

    /**
     * Creates a form to delete a User entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('user_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

src/Acme/DemoBundle/Resources/views/User/edit.html.twig
{% extends "AcmeDemoBundle::admin.html.twig" %}
{% block main_menu %}{% render url('_sidebarAdmin') %}{% endblock %}

{% block content%}
    <h1>{% trans %}User edit{% endtrans %}</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('user') }}">
            {% trans %}Back to the list{% endtrans %}
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Acme/DemoBundle/Resources/views/User/index.html.twig
{% extends "AcmeDemoBundle::admin.html.twig" %}
{% block main_menu %}{% render url('_sidebarAdmin') %}{% endblock %}

{% block content%}
    <h1>{% trans %}User list{% endtrans %}</h1>

    <table class="records_list">
        <thead>
            <tr>
                <th>Imię</th>
                <th>Nazwisko</th>
                <th>Nick</th>
                <th>Uprawnienia</th>
                <th>{% trans %}Actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td><a href="{{ path('user_show', { 'id': entity.id }) }}">{{ entity.name }}</a></td>
                <td>{{ entity.surname }}</td>
                <td>{{ entity.nick }}</td>
                <td>{{ entity.roleByName }}</td>
                <td>
                <ul>
                    <li>
                        <a href="{{ path('user_show', { 'id': entity.id }) }}">{% trans %}show{% endtrans %}</a>
                    </li>
                    <li>
                        <a href="{{ path('user_edit', { 'id': entity.id }) }}">{% trans %}edit{% endtrans %}</a>
                    </li>
                </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <ul>
        <li>
            <a href="{{ path('user_new') }}">
                {% trans %}Add{% endtrans %}
            </a>
        </li>
    </ul>
    {% endblock %}

src/Acme/DemoBundle/Resources/views/User/new.html.twig
{% extends "AcmeDemoBundle::admin.html.twig" %}
{% block main_menu %}{% render url('_sidebarAdmin') %}{% endblock %}

{% block content%}
    <h1>{% trans %}User creation{% endtrans %}</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('user') }}">
            {% trans %}Back to the list{% endtrans %}
        </a>
    </li>
</ul>
{% endblock %}

src/Acme/DemoBundle/Resources/views/User/show.html.twig
{% extends "AcmeDemoBundle::admin.html.twig" %}
{% block main_menu %}{% render url('_sidebarAdmin') %}{% endblock %}

{% block content%}
    <h1>{% trans %}User{% endtrans %}</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>{% trans %}Name{% endtrans %}</th>
                <td>{{ entity.name }}</td>
            </tr>
            <tr>
                <th>{% trans %}Surname{% endtrans %}</th>
                <td>{{ entity.surname }}</td>
            </tr>
            <tr>
                <th>{% trans %}Nick{% endtrans %}</th>
                <td>{{ entity.nick }}</td>
            </tr>
            <tr>
                <th>{% trans %}Id{% endtrans %}</th>
                <td>{{ entity.id }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('user') }}">
            {% trans %}Back to the list{% endtrans %}
        </a>
    </li>
    <li>
        <a href="{{ path('user_edit', { 'id': entity.id }) }}">
            {% trans %}edit{% endtrans %}
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}